sudo: false
language: node_js
node_js: 6
env:
  global:
cache:
  apt: true
  directories:
  - node_modules
  - website/.lanyon
install: npm install
script: npm run test
before_cache:
  - rm -f ./node_modules/.bin/which # <-- workaround for https://github.com/travis-ci/travis-ci/issues/5092
before_deploy: node_modules/.bin/lanyon postinstall
deploy:
  skip_cleanup: true
  provider: script
  script: .lanyon/bin/deploy
  on:
    branch: master
    condition: $TRAVIS_OS_NAME = linux
