sudo: false
language: node_js
node_js: 6
env:
  global:
cache:
  apt: true
  directories:
  - node_modules
  - website/.lanyon
install: npm install
before_script: node_modules/.bin/lanyon postinstall
script: npm run test
deploy:
  skip_cleanup: true
  provider: script
  script: .lanyon/bin/deploy
  on:
    branch: master
    condition: $TRAVIS_OS_NAME = linux
