language: go

go:
- 1.1
- 1.2
- 1.3
- tip

matrix:
  allow_failures:
    - go: tip

before_install:
- go get github.com/axw/gocov/gocov || true
- go get github.com/mattn/goveralls || true
- go get code.google.com/p/go.tools/cmd/cover || true
- go get gopkg.in/fsnotify.v1
- go get github.com/mitchellh/go-homedir

script:
- $HOME/gopath/bin/goveralls -v -repotoken $COVERALLS_TOKEN || make test

# travis encrypt [subdomain]:[api token]@[room id]
notifications:
  email: false
  campfire:
    rooms:
        secure: "LuXd8n73TVzFDwkzSpl08mnAGSShbeel3es63++2yxQxzX2QuXC7+abts9TqtXiC8pK50V6bXpU8+e1tBq7m5J727mS7vuu6pt6nf82QaXtqhAd+Egt8NR8Sbpb4guLQFHrdjn4jssyqAnG8fEfjK2Piyx8ugCvtfSkftUiMY8U="
    on_failure: always
    on_success: always

env:
  global:
    # COVERALLS_TOKEN
    - secure: wGKrsYBSuI4NhxcveqjQGCuY1Jcrh6iF59FEZS8ipWVSIqp2sMQU3K7LqgeUVnyCqXT0LsuLFMPhKDHc8My+aFno85jrmkJo7+gvBnCQC/f5/7Ee3r4LdEgmv4dIRrsItYir/ez/KIQ2BtynWEdLk8/afgNCOF9IjvtX6XneDYg=
    # TRANSLOADIT_KEY
    - secure: chRxpyqy+3MH98lIo+StQAsSHtAirQfD5yguOmmUet2gXeQmW1r4/Bfyvd3VN15DVGMgWlB6I5oKEwVNJp28DWrlBhXM+U80fQGiUwVVuvXUnnDFJGbp7WJSYJs5XX4vHtWN148kv6lQSOHBVRE0HBn9vTmOIYYJqcUNOfZNlJQ=
    # TRANSLOADIT_SECRET
    - secure: GfSX6bizEA+D8S6kEDbm5uZNvDQc1KEEvqZ5E0a8erNUWwswf7vTzLHIq6qcY80i+FlmBIEZ5rEQxaWi73bSyjb4oPnaOKkyzMPqTVNxScwBLDOXUeSHzROVYCBjIfZw43gr4fzcezPtzy5wgFtcqEClImO1pLN5mUGcSTsyQzI=
