language: go
go:
- 1.1
- 1.2
- 1.3
- tip
matrix:
  allow_failures:
  - go: tip
before_install:
- go get .
env: "PATH=/home/travis/gopath/bin:$PATH"
script:
- make build
- echo $TRAVIS_GO_VERSION
- if [[ $TRAVIS_GO_VERSION == 1.3* ]]; then go get github.com/laher/goxc; fi
- if [[ $TRAVIS_GO_VERSION == 1.3* ]]; then goxc -d . -bc="darwin,windows,linux"; fi
# travis encrypt [subdomain]:[api token]@[room id]
notifications:
  email: false
  campfire:
    rooms:
      secure: LuXd8n73TVzFDwkzSpl08mnAGSShbeel3es63++2yxQxzX2QuXC7+abts9TqtXiC8pK50V6bXpU8+e1tBq7m5J727mS7vuu6pt6nf82QaXtqhAd+Egt8NR8Sbpb4guLQFHrdjn4jssyqAnG8fEfjK2Piyx8ugCvtfSkftUiMY8U=
    on_failure: always
    on_success: always
deploy:
  provider: releases
  api_key:
    secure: HqzAaZsAVDwpdeCOWzsYmteDG+IaGspBCiXQ7S5awK4srYM0s6j2kSBSBQQsX4oyEGibJ8b4jBO9/cX74kfg+ImrjWH+Cmvj0lj8LAVG/8UnVwO+VIPeaORL3kuUZMECJbWHhTl55TlQ3OpdpWnlkUGkPUABCDAjem/a2Drub84=
  file:
  - snapshot/transloadify_windows_386.zip
  - snapshot/transloadify_windows_amd64.zip
  - snapshot/transloadify_darwin_386.zip
  - snapshot/transloadify_darwin_amd64.zip
  - snapshot/transloadify_linux_386.tar.gz
  - snapshot/transloadify_linux_arm.tar.gz
  - snapshot/transloadify_linux_amd64.tar.gz
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    go: 1.3
